project:
  type: book

book:
  title: "Técnicas de comparación de modelos geoespaciales"
  author: "Miguel A. Castañeda Martínez"
  chapters:
    - index.qmd
    - 01-pruebas-de-hipotesis.qmd

format:
  html:
    theme: cosmo
    fig-align: center
    fig-cap-location: bottom

execute:
  freeze: auto