# Syllabus {.unnumbered}

## Objetivo General {-}

Establecer una referencia rápida de los temas y conceptos necesarios para
evaluar y comparar modelos geoespaciales.

## Contenido {-}

1. Pruebas de hipótesis
2. Mallados e indexación

## Repositorio de componentes {-}

* Los componentes que integran este trabajo, incluidas notas, _notebooks_,
código, etc. se encuentran en el [repositorio](https://github.com/CAMM961001/estancia).

## Referencias principales {-}

* [Applied Geospatial Data Science with Python](https://github.com/PacktPublishing/Applied-Geospatial-Data-Science-with-Python), D. Jordan. Packt Publishing.
* [Geographic Data Science with Python](https://geographicdata.science/book/intro.html), S. J. Rey, et.al. CRC Press
* [An Introduction to Spatial Data Science with GeoDa. Volume 1: Exploring Spatial Data](https://lanselin.github.io/introbook_vol1/)
* [An Introduction to Spatial Data Science with GeoDa. Volume 2: Clustering Spatial Data](https://lanselin.github.io/introbook_vol2/)
* [GeoDa Workbook](https://geodacenter.github.io/documentation.html)
* [Introduction to Spatial Data Science](https://youtube.com/playlist?list=PLzREt6r1NenmFyTw8v2JZpEE4PZGNi5Ht&si=SUS-PmoOYAN8_XtO), L. Anselin.
_The Center for Spatial Data Science_, U. Chicago.
* [Spatial Weights](https://www.youtube.com/watch?v=yjFNuyfskaQ), L. Anselin.
_The Center for Spatial Data Science_, U. Chicago.
* [H3: Uber’s Hexagonal Hierarchical Spatial Index](https://www.uber.com/en-MX/blog/h3/)
* [The Assessment of Impacts and Risks of Climate Change on Agriculture (AIRCCA) model: a tool for the rapid global risk assessment for crop yields at a spatially explicit scale](https://sites.google.com/view/aircc-lab)
* [The incidental parameter problem since 1948](http://www.econ.brown.edu/Faculty/Tony_Lancaster/papers/IncidentalParameters1948.pdf)
